http://localhost:5000/api/v1/user434 

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin15@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin15@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImVtYWlsIjoiYWRtaW4xNUBnbWFpbC5jb20iLCJpYXQiOjE3MDUzMzU4MzgsImV4cCI6MTcwNTUwODYzOH0.e5ywXCnHjYYjvEoBS5585mQCm3uNH1UsMWZQv7H3Sr8
